DELETE FROM SCHEDULE_VOTE;
DELETE FROM `COMMENT`;
DELETE FROM SCHEDULE;
DELETE FROM user_club;
DELETE FROM USERS;
DELETE FROM CLUB;

-- IDENTITY 초기화
ALTER TABLE USER_CLUB ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN user_id RESTART WITH 1;
ALTER TABLE CLUB ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE SCHEDULE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE `COMMENT` ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE SCHEDULE_VOTE ALTER COLUMN ID RESTART WITH 1;

