DELETE FROM user_club;
DELETE FROM USERS;
DELETE FROM CLUB;

ALTER TABLE USER_CLUB ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN user_id RESTART WITH 1;
ALTER TABLE CLUB ALTER COLUMN ID RESTART WITH 1;